### PR TITLE
Update version to 0.8.0

### LINKED ISSUE #797: Release new version/tag due to breaking change of aws-sdk `v1.23.0`
Hello,

recently we ran into a problem in Tekton, where we get a `401 Not Authorized` when trying to access our private ECR. 
I had a look into it and found that a version mismatch between 2 dependencies inside of Tekton causes this behaviour. More or less it comes down to the aws-sdk module and its dependend modules and its breaking change with `v1.23.0` (see https://github.com/aws/aws-sdk-go-v2/issues/2370). 

Since your latest release/tag of `v0.7.1` includes the aws-sdk with the version `v1.18.x` (which is `<v1.23.0`) this leads to a buggy behaviour if another dependency is using aws-sdk with `>v1.23.0`. For more details of the error we encountered see the Tekton issue https://github.com/tektoncd/pipeline/issues/7698.

The package is up-to-date on the main branch, so I wanted to ask if you could release a new version? This would fix this problem for up-stream projects using multiple dependencies.

### PR DESCRIPTION
**Pull request by austinvazquez**
*Issue #, if available:*
Closes #797

Version and changelog updates for https://github.com/awslabs/amazon-ecr-credential-helper/milestone/5

*Description of changes:*
Version and changelog updates for v0.8.0 release.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by pendo324 — APPROVED** [review]

**Comment by austinvazquez** [comment]
#799 should be the last item before the release.

**Review by swagatbora90 — APPROVED** [review]

**Comment by austinvazquez** [comment]
Hey folks, update on the progress here. I have put together the change management forms required for the 0.8.0 release and am currently in the review stage. Tentatively looking at May 10 as the release date. Will post further updates based on progress. Thanks!

**Comment by austinvazquez** [comment]
Hey folks, apologies for the delay. Full transparency the release is blocked pending one more approval.

I am asking to get this completed by May 17. Appreciate the patience here.

**Comment by austinvazquez** [comment]
Great news was able to pull this over the line! (Kicking and screaming 😆)

Special thanks to @pendo324 for helping with the release.

**Pull request merged**
