### PR TITLE
Add support for assumed roles

### PR DESCRIPTION
**Pull request by digitalfiz**
This PR updates the aws-sdk-go package to the newest version so that  you can use assumed roles.

### CODE REVIEW

**Comment by digitalfiz** [comment]
This fixes #20

**Comment by samuelkarp** [comment]
@digitalfiz Thanks!  A few things:

* Can you confirm that this contribution is under the terms of the Apache 2.0 license?
* It looks like this was updated by just putting the contents of the aws-sdk-go git repository in the vendor directory.  Can you update this using godep instead?  It'd look like this: `cd $GOPATH/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login; go get -u github.com/aws/aws-sdk-go && godep update github.com/aws/aws-sdk-go/...`
* The unit tests are failing right now because the mocks are now out of date with the ECR API (they added a new operation).  Can you regenerate the mocks with `make gogenerate`?

**Comment by digitalfiz** [comment]
I was wondering about the mocks. I will do both now.

**Comment by samuelkarp** [comment]
@digitalfiz It looks like `make gogenerate` is including things from the `vendor` folder when it shouldn't, so you might want to rebase your changes on top of https://github.com/awslabs/amazon-ecr-credential-helper/pull/22.

**Comment by digitalfiz** [comment]
Should be all fixed up now.

**Comment by samuelkarp** [comment]
@digitalfiz It looks like the mocks got deleted.  Were there any errors when you ran `make gogenerate`?

**Comment by digitalfiz** [comment]
Yeah I was missing `goimports` and `mockgen`. I changed my GOPATH and forgot to go get some stuff :-/

**Pull request merged**
