### PR TITLE
ci: support win/arm64 target

### PR DESCRIPTION
**Pull request by maxcleme**
*Issue #, if available:*

*Description of changes:*

Add support for win/arm64 target

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by austinvazquez — APPROVED** [review]
Hi @maxcleme, thanks for the contribution. It will be nice to have this for Windows ARM.

**Review by pendo324 — APPROVED** [review]

**Comment by maxcleme** [comment]
Hey! Thanks for merging my PR! 🙇 

Do you have idea when I can expect a proper Github release? 😁 

Thanks again for such reactivity!

**Comment by maxcleme** [comment]
@austinvazquez @pendo324 up? Sorry to bother again! Any timeline for a proper Github release for win/arm64 now? 😁

**Comment by austinvazquez** [comment]
@maxcleme, I have pushed through the items needed for 0.8.0 milestone (which I just realized I never actually shared; see https://github.com/awslabs/amazon-ecr-credential-helper/milestone/5) and opened #798 with the version and changelog updates required. I will try to put updates in the PR based on the progress of the release.

**Comment by austinvazquez** [comment]
@maxcleme, the experimental Windows ARM binary is included in v0.8.0 release. Hope that helps. Feel free to use it and include feedback in #795.

**Pull request merged**
