### PR TITLE
Update ECR pattern to include C2S environments

### PR DESCRIPTION
**Pull request by jrsherry**
*Issue #, if available:*
433
*Description of changes:*
Update the ecrPattern to include c2s environments

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by speedythesnailnpg** [comment]
It's a shame that a year and 2 months later, nobody has bothered to look at this pr, given how much money is spent in c2s every year.

It would be great if somebody can review this and either approve or deny it.

**Comment by austinvazquez** [comment]
Will close and reopen for CI to run.

**Review by austinvazquez — APPROVED** [review]
As noted by author, change matches the pattern used by Kubernetes credential provider for AWS ECR. See [here](https://github.com/kubernetes/cloud-provider-aws/blob/05d6fe9359906be9c0471751507878c29b16d1b3/cmd/ecr-credential-provider/main.go#L45). So LGTM.

**Comment by speedythesnailnpg** [comment]
Thank you @austinvazquez !

**Comment by austinvazquez** [comment]
Asking internally for one more reviewer. I'll help get this pushed through.

**Review by sondavidb — APPROVED** [review]

**Review by turan18 — APPROVED** [review]
LGTM, let's make sure we squash and merge.

**Comment by austinvazquez** [comment]
Thanks @jrsherry for the change and @speedythesnailnpg for bringing it to my attention. Sorry for the delay.

**Pull request merged**
