### PR TITLE
Make expiration logic more readable

### LINKED ISSUE #7: Expired cached token is considered valid -> authorization fails
I'm seeing some weird behaviour in the credentials helper:
I have a token from yesterday in my cache:
```
# date -u +"%Y-%m-%dT%H:%M:%SZ"
2016-08-02T08:23:40Z

# cat .ecr/cache.json
{
  "Registries": {
    "<snip>": {
      "AuthorizationToken": "<snip>",
      "RequestedAt": "2016-08-01T17:05:07.865313389Z",
      "ExpiresAt": "2016-08-02T05:05:08Z",
      "ProxyEndpoint": "https://<snip>.dkr.ecr.eu-west-1.amazonaws.com"
    }
  },
  "Version": "1.0"
}

```

When I do a `docker pull` I get the following result:
```
#docker pull <snip>.dkr.ecr.eu-west-1.amazonaws.com/test:latest
Error response from daemon: error parsing HTTP 403 response body: invalid character 'Y' looking for beginning of value: "Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one."
```
 
The credentials helper's log shows the following:
```
2016-08-02T08:24:55Z [DEBUG] Retrieving credentials for <snip> in eu-west-1 (<snip>.dkr.ecr.eu-west-1.amazonaws.com)
2016-08-02T08:24:55Z [DEBUG] GetCredentials for <snip>
2016-08-02T08:24:55Z [DEBUG] Checking file cache for <snip>
2016-08-02T08:24:55Z [DEBUG] Using cached token for <snip>
```

It seems to me, as if the credentials helper does somehow not deem the expired token invalid. Do you have any insights on that?

### PR DESCRIPTION
**Pull request by samuelkarp**
Fixes #7

This carries #8 from @f-barth and attempts to make the logic more readable.

r? @sentientmonkey

### CODE REVIEW

**Comment by sentientmonkey** [comment]
Looks good! 🚢 

I don't know _what_ I was thinking when I wrote that original function. Bug looks fixed and code is much more understandable now. Thanks again @f-barth for brining this to our attention!

**Comment by roastlechon** [comment]
When will this be able to get merged? Im actually running into this issue now...

**Comment by samuelkarp** [comment]
@roastlechon I've just merged it, please let us know if you still run into problems.

**Comment by roastlechon** [comment]
@samuelkarp Thanks! It works great!

**Pull request merged**
