### PR TITLE
Update aws sdk to v1.35.4

### PR DESCRIPTION
**Pull request by b-dean**
*Description of changes:*
I was running into an issue where the credentials from `credential_process` in my `~/.aws/config` were not valid JSON because they were being truncated.

```
$ docker-credential-ecr-login list
ecr: could not list credentials: ecr: Failed to get authorization token: ProcessProviderParseError: parse failed of credential_process output: {"Version":1,"AccessKeyId":"ASIAxxxxxxxxxxxxxxxxx","SecretAccessKey":"xxxxxxxxxxxx","SessionToken":"xxxx...more...xxxxx
caused by: unexpected end of JSON input
```

This is fixed in the [aws sdk in v1.25.42](https://github.com/aws/aws-sdk-go/commit/646ede7d96dfb43c083c1291a06b9bc735a0e7a6), but I figured we might as well update to the latest sdk.

This would also fix @fred-vogt's issues in PR #223 and issue #215 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rittneje** [comment]
@samuelkarp @kzys @nmeyerhans Can this PR be merged? The version of the SDK currently being used is quite out of date (over a year old). I would like to be able to leverage the `AWS_ROLE_ARN` environment variable that was added recently.

**Comment by kzys** [comment]
Looks good to me.

**Comment by krmichelos** [comment]
It is great that this has been merged.  @kzys or @samuelkarp is there a planned release soon that will contain this change?

**Comment by zvymazal** [comment]
@samuelkarp Is there a target date for the next release in which this update will be released?

**Comment by kzys** [comment]
We don't have the target date yet, but we are going to create a new release which will include this change.

**Pull request merged**
